export default {
  "application/octet-stream": "未知",
  "text/plain": "文本文档",
  "text/html": "网页文档",
  "text/css": "叠层样式表",
  "text/javascript": "JavaScript脚本",
  "image/gif": "GIF动图",
  "image/jpeg": "JPEG图片",
  "image/png": "PNG图片",
  "image/svg+xml": "SVG矢量图",
  "image/webp": "WEBP图片",
  "image/x-icon": "ICO图标",
  "audio/wave": "音频流媒体",
  "audio/wav": "音频流媒体",
  "audio/x-wav": "音频流媒体",
  "audio/x-pn-wav": "音频流媒体",
  "audio/webm": "WEBM音频",
  "video/webm": "WEBM视频",
  "audio/ogg": "ogg音频",
  "video/ogg": "ogg视频",
  "application/ogg": "ogg音视频",
  "application/json": "json文档",
  "application/x-msdownload": "Microsoft应用程序",
  "application/x-shockwave-flash": "Flash动画",
  "application/x-gzip": "GZIP压缩包",
  "video/mp4": "MP4视频",
  "video/avi": "AVI视频",
  "application/vnd.ms-excel": "电子表格",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
    "电子表格",
  "application/pdf": "PDF文件",
  "text/xml": "XML文档",
  "application/x-zip-compressed": "ZIP压缩包",
  "audio/x-m4a": "M4A音频",
};
